# Generated by Django 5.1 on 2024-09-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_painter_approved',
            field=models.BooleanField(default=False),
        ),
    ]
