# Generated by Django 5.1 on 2024-09-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_painting'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='is_approved_for_bidding',
            field=models.BooleanField(default=False),
        ),
    ]
